# Generated by Django 5.0.3 on 2024-03-29 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Stock',
            new_name='stock',
        ),
    ]
