# Generated by Django 5.0.3 on 2024-03-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_rename_stock_variation_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_long',
            field=models.TextField(),
        ),
    ]
