# Generated by Django 5.0.3 on 2024-03-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_contact_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(upload_to='pictures/%Y/%m'),
        ),
    ]
