# Generated by Django 5.0.3 on 2024-03-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_contact_email_alter_contact_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m'),
        ),
    ]
