# Generated by Django 5.0.3 on 2024-03-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_rename_create_date_contact_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
